language: go
go:
  - 1.5
os:
  - linux
  - osx
env:
  - USE_RUBY=2.0.0-p647
  - USE_RUBY=2.1.7
  - USE_RUBY=2.2.3
before_install:
  - rvm use $USE_RUBY --install --fuzzy
script:
  - RAILS_ENV="" make
