language: go
go:
  - 1.5
env:
  - USE_RUBY=2.0.0-p647
  - USE_RUBY=2.1.7
  - USE_RUBY=2.2.3
before_install:
  - rvm use $USE_RUBY --install --fuzzy
install:
  - make dev_bootstrap
  - make rubygem/lib/zeus/version.rb
script:
  - make test-go
  - make build-linux
  - make rubygem/lib/zeus/version.rb && cd rubygem && bundle install --without development && bin/rspec spec
