language: go
go:
  - "1.7.x"
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"
os:
  - linux
  - osx
env:
  - USE_RUBY=2.1.10
  - USE_RUBY=2.2.5
  - USE_RUBY=2.3.1

# OS X builds are slow and heavily rate limited. Ruby should behave similarly
# across platforms so we sacrifice testing multiple Ruby versions in favor of
# faster build times.
matrix:
  exclude:
    - os: osx
      env: USE_RUBY=2.1.10
    - os: osx
      env: USE_RUBY=2.2.5

before_install:
  - rvm use $USE_RUBY --install --fuzzy
script:
  - RAILS_ENV="" make
